[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.deploy"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "bash -c 'python -m uvicorn open_webui.main:app --host 0.0.0.0 --port ${PORT:-8080}'"

[variables]
WEBUI_SECRET_KEY = { generate = true }
CORS_ALLOW_ORIGIN = "*"
DATA_DIR = "/app/backend/data"
# Map the managed Postgres connection string provided by Railway
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"
